/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.gui;

/**
 *
 * @author Keloc
 */
public class BibliotecaInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form BibliotecaInterfaz
     */
    public BibliotecaInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        seccionContenedor = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        menuOpciones = new javax.swing.JPanel();
        contenedorOpt = new javax.swing.JPanel();
        principalOptP = new javax.swing.JPanel();
        principalL = new javax.swing.JLabel();
        prestamosOptP = new javax.swing.JPanel();
        prestamosL = new javax.swing.JLabel();
        devolucionesOptP = new javax.swing.JPanel();
        devolucionesL = new javax.swing.JLabel();
        miembrosOptP = new javax.swing.JPanel();
        miembrosL = new javax.swing.JLabel();
        catalogoOptP = new javax.swing.JPanel();
        catalogoL = new javax.swing.JLabel();
        logsOptP = new javax.swing.JPanel();
        logsL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(800, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seccionContenedor.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout seccionContenedorLayout = new javax.swing.GroupLayout(seccionContenedor);
        seccionContenedor.setLayout(seccionContenedorLayout);
        seccionContenedorLayout.setHorizontalGroup(
            seccionContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        seccionContenedorLayout.setVerticalGroup(
            seccionContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        bg.add(seccionContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 500));

        menuOpciones.setBackground(new java.awt.Color(204, 204, 204));
        menuOpciones.setPreferredSize(new java.awt.Dimension(175, 500));

        contenedorOpt.setBackground(new java.awt.Color(102, 153, 255));
        contenedorOpt.setMaximumSize(new java.awt.Dimension(350, 600));
        contenedorOpt.setMinimumSize(new java.awt.Dimension(175, 300));
        contenedorOpt.setLayout(new javax.swing.BoxLayout(contenedorOpt, javax.swing.BoxLayout.PAGE_AXIS));

        principalOptP.setBackground(new java.awt.Color(102, 153, 255));
        principalOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        principalOptP.setMinimumSize(new java.awt.Dimension(175, 50));
        principalOptP.setPreferredSize(new java.awt.Dimension(175, 50));

        principalL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        principalL.setText("Principal");

        javax.swing.GroupLayout principalOptPLayout = new javax.swing.GroupLayout(principalOptP);
        principalOptP.setLayout(principalOptPLayout);
        principalOptPLayout.setHorizontalGroup(
            principalOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalOptPLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(principalL, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        principalOptPLayout.setVerticalGroup(
            principalOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalOptPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(principalL)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        contenedorOpt.add(principalOptP);

        prestamosOptP.setBackground(new java.awt.Color(102, 153, 255));
        prestamosOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        prestamosOptP.setMinimumSize(new java.awt.Dimension(175, 50));

        prestamosL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        prestamosL.setText("Prestamos");

        javax.swing.GroupLayout prestamosOptPLayout = new javax.swing.GroupLayout(prestamosOptP);
        prestamosOptP.setLayout(prestamosOptPLayout);
        prestamosOptPLayout.setHorizontalGroup(
            prestamosOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamosOptPLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(prestamosL, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        prestamosOptPLayout.setVerticalGroup(
            prestamosOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamosOptPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(prestamosL)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        contenedorOpt.add(prestamosOptP);

        devolucionesOptP.setBackground(new java.awt.Color(102, 153, 255));
        devolucionesOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        devolucionesOptP.setMinimumSize(new java.awt.Dimension(175, 50));

        devolucionesL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        devolucionesL.setText("Devoluciones");

        javax.swing.GroupLayout devolucionesOptPLayout = new javax.swing.GroupLayout(devolucionesOptP);
        devolucionesOptP.setLayout(devolucionesOptPLayout);
        devolucionesOptPLayout.setHorizontalGroup(
            devolucionesOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devolucionesOptPLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(devolucionesL)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        devolucionesOptPLayout.setVerticalGroup(
            devolucionesOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devolucionesOptPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(devolucionesL)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        contenedorOpt.add(devolucionesOptP);

        miembrosOptP.setBackground(new java.awt.Color(102, 153, 255));
        miembrosOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        miembrosOptP.setMinimumSize(new java.awt.Dimension(175, 50));

        miembrosL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        miembrosL.setText("Miembros");

        javax.swing.GroupLayout miembrosOptPLayout = new javax.swing.GroupLayout(miembrosOptP);
        miembrosOptP.setLayout(miembrosOptPLayout);
        miembrosOptPLayout.setHorizontalGroup(
            miembrosOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miembrosOptPLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(miembrosL)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        miembrosOptPLayout.setVerticalGroup(
            miembrosOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miembrosOptPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(miembrosL)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        contenedorOpt.add(miembrosOptP);

        catalogoOptP.setBackground(new java.awt.Color(102, 153, 255));
        catalogoOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        catalogoOptP.setMinimumSize(new java.awt.Dimension(175, 50));

        catalogoL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        catalogoL.setText("Catalogo");

        javax.swing.GroupLayout catalogoOptPLayout = new javax.swing.GroupLayout(catalogoOptP);
        catalogoOptP.setLayout(catalogoOptPLayout);
        catalogoOptPLayout.setHorizontalGroup(
            catalogoOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoOptPLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(catalogoL)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        catalogoOptPLayout.setVerticalGroup(
            catalogoOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoOptPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(catalogoL)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        contenedorOpt.add(catalogoOptP);

        logsOptP.setBackground(new java.awt.Color(102, 153, 255));
        logsOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        logsOptP.setMinimumSize(new java.awt.Dimension(175, 50));

        logsL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        logsL.setText("Logs");

        javax.swing.GroupLayout logsOptPLayout = new javax.swing.GroupLayout(logsOptP);
        logsOptP.setLayout(logsOptPLayout);
        logsOptPLayout.setHorizontalGroup(
            logsOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logsOptPLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(logsL)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        logsOptPLayout.setVerticalGroup(
            logsOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logsOptPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logsL)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        contenedorOpt.add(logsOptP);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout menuOpcionesLayout = new javax.swing.GroupLayout(menuOpciones);
        menuOpciones.setLayout(menuOpcionesLayout);
        menuOpcionesLayout.setHorizontalGroup(
            menuOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOpcionesLayout.createSequentialGroup()
                .addComponent(contenedorOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(menuOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuOpcionesLayout.setVerticalGroup(
            menuOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorOpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotecaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotecaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotecaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BibliotecaInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel catalogoL;
    private javax.swing.JPanel catalogoOptP;
    private javax.swing.JPanel contenedorOpt;
    private javax.swing.JLabel devolucionesL;
    private javax.swing.JPanel devolucionesOptP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logsL;
    private javax.swing.JPanel logsOptP;
    private javax.swing.JPanel menuOpciones;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel miembrosL;
    private javax.swing.JPanel miembrosOptP;
    private javax.swing.JLabel prestamosL;
    private javax.swing.JPanel prestamosOptP;
    private javax.swing.JLabel principalL;
    private javax.swing.JPanel principalOptP;
    private javax.swing.JPanel seccionContenedor;
    // End of variables declaration//GEN-END:variables
}
