/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gui;

import java.awt.Color;

/**
 *
 * @author Keloc
 */
public class Miembros extends javax.swing.JPanel {

    /**
     * Creates new form Miembros
     */
    public Miembros() {
        initComponents();
        initStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miembrosIP = new javax.swing.JPanel();
        miembrosTextL = new javax.swing.JLabel();
        buscadorTF = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JPanel();
        buscarL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nuevoBtn = new javax.swing.JPanel();
        nuevoL = new javax.swing.JLabel();
        editarBtn = new javax.swing.JPanel();
        editL = new javax.swing.JLabel();
        borrarBtn = new javax.swing.JPanel();
        borrarL = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        miembrosIP.setBackground(new java.awt.Color(255, 255, 255));
        miembrosIP.setMinimumSize(new java.awt.Dimension(620, 360));
        miembrosIP.setPreferredSize(new java.awt.Dimension(620, 360));

        miembrosTextL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miembrosTextL.setText("Miembros");

        buscadorTF.setBackground(new java.awt.Color(255, 255, 255));
        buscadorTF.setForeground(new java.awt.Color(153, 153, 153));
        buscadorTF.setText("Ingrese un dato de búsqueda...");
        buscadorTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscadorTFMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscadorTFMouseExited(evt);
            }
        });
        buscadorTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorTFActionPerformed(evt);
            }
        });

        buscarBtn.setBackground(new java.awt.Color(51, 153, 255));
        buscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarBtnMouseExited(evt);
            }
        });

        buscarL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buscarL.setForeground(new java.awt.Color(255, 255, 255));
        buscarL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarL.setText("Buscar");
        buscarL.setMaximumSize(new java.awt.Dimension(100, 27));
        buscarL.setMinimumSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout buscarBtnLayout = new javax.swing.GroupLayout(buscarBtn);
        buscarBtn.setLayout(buscarBtnLayout);
        buscarBtnLayout.setHorizontalGroup(
            buscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        buscarBtnLayout.setVerticalGroup(
            buscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellidos", "Email", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        nuevoBtn.setBackground(new java.awt.Color(51, 153, 255));
        nuevoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoBtnMouseExited(evt);
            }
        });

        nuevoL.setBackground(new java.awt.Color(51, 153, 255));
        nuevoL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nuevoL.setForeground(new java.awt.Color(255, 255, 255));
        nuevoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoL.setText("Añadir");
        nuevoL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout nuevoBtnLayout = new javax.swing.GroupLayout(nuevoBtn);
        nuevoBtn.setLayout(nuevoBtnLayout);
        nuevoBtnLayout.setHorizontalGroup(
            nuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nuevoBtnLayout.setVerticalGroup(
            nuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        editarBtn.setBackground(new java.awt.Color(0, 153, 255));
        editarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editarBtnMouseExited(evt);
            }
        });

        editL.setBackground(new java.awt.Color(51, 153, 255));
        editL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editL.setForeground(new java.awt.Color(255, 255, 255));
        editL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editL.setText("Editar");
        editL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout editarBtnLayout = new javax.swing.GroupLayout(editarBtn);
        editarBtn.setLayout(editarBtnLayout);
        editarBtnLayout.setHorizontalGroup(
            editarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        editarBtnLayout.setVerticalGroup(
            editarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        borrarBtn.setBackground(new java.awt.Color(51, 153, 255));
        borrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrarBtnMouseExited(evt);
            }
        });

        borrarL.setBackground(new java.awt.Color(51, 153, 255));
        borrarL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        borrarL.setForeground(new java.awt.Color(255, 255, 255));
        borrarL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrarL.setText("Borrar");
        borrarL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout borrarBtnLayout = new javax.swing.GroupLayout(borrarBtn);
        borrarBtn.setLayout(borrarBtnLayout);
        borrarBtnLayout.setHorizontalGroup(
            borrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borrarL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        borrarBtnLayout.setVerticalGroup(
            borrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borrarL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout miembrosIPLayout = new javax.swing.GroupLayout(miembrosIP);
        miembrosIP.setLayout(miembrosIPLayout);
        miembrosIPLayout.setHorizontalGroup(
            miembrosIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, miembrosIPLayout.createSequentialGroup()
                .addGroup(miembrosIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(miembrosIPLayout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(nuevoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, miembrosIPLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(miembrosIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, miembrosIPLayout.createSequentialGroup()
                                .addComponent(buscadorTF)
                                .addGap(18, 18, 18)
                                .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(miembrosIPLayout.createSequentialGroup()
                                .addComponent(miembrosTextL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(392, 392, 392)))))
                .addGap(21, 21, 21))
        );
        miembrosIPLayout.setVerticalGroup(
            miembrosIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, miembrosIPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(miembrosTextL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(miembrosIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(miembrosIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miembrosIP, javax.swing.GroupLayout.PREFERRED_SIZE, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miembrosIP, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoBtnMouseEntered
        nuevoBtn.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_nuevoBtnMouseEntered

    private void editarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnMouseEntered
        editarBtn.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_editarBtnMouseEntered

    private void borrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarBtnMouseEntered
        borrarBtn.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_borrarBtnMouseEntered

    private void buscadorTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscadorTFMouseExited
        
    }//GEN-LAST:event_buscadorTFMouseExited

    private void buscarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseExited
        buscarBtn.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_buscarBtnMouseExited

    private void nuevoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoBtnMouseExited
       nuevoBtn.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_nuevoBtnMouseExited

    private void editarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnMouseExited
        editarBtn.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_editarBtnMouseExited

    private void borrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarBtnMouseExited
        borrarBtn.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_borrarBtnMouseExited

    private void buscarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseEntered
        buscarBtn.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_buscarBtnMouseEntered

    private void buscadorTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscadorTFMouseClicked
        if (buscadorTF.getText().equals("Ingrese un dato de búsqueda...")){
            buscadorTF.setText("");
            buscadorTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_buscadorTFMouseClicked

    private void buscadorTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscadorTFActionPerformed

    private void initStyles(){
        miembrosTextL.putClientProperty( "FlatLaf.style", "font: h1 $h1.font" );
        buscarL.putClientProperty( "FlatLaf.style", "font: large $large.font" );
        nuevoL.putClientProperty( "FlatLaf.style", "font: large $large.font" );
        editL.putClientProperty( "FlatLaf.style", "font: large $large.font" );
        borrarL.putClientProperty( "FlatLaf.style", "font: large $large.font" );
        buscadorTF.putClientProperty( "FlatLaf.style", "font: medium $medium.font" );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel borrarBtn;
    private javax.swing.JLabel borrarL;
    private javax.swing.JTextField buscadorTF;
    private javax.swing.JPanel buscarBtn;
    private javax.swing.JLabel buscarL;
    private javax.swing.JLabel editL;
    private javax.swing.JPanel editarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel miembrosIP;
    private javax.swing.JLabel miembrosTextL;
    private javax.swing.JPanel nuevoBtn;
    private javax.swing.JLabel nuevoL;
    // End of variables declaration//GEN-END:variables
}
